### ISSUE TITLE
Change Terradoo Cloud Logo

### ISSUE THREAD

**Issue by JuanDCG** [TerradooCloud/documentation#18]
- [ ] Change Terradoo Cloud Logo
  - [x] First design White
  - [ ] Second design Green

**Comment by ska-ibees** [comment]
![Terraodoo2](https://user-images.githubusercontent.com/5569632/99813709-ef244e00-2b3f-11eb-8ff6-55387bde5f5d.png)
![Terraodoo3](https://user-images.githubusercontent.com/5569632/99813713-efbce480-2b3f-11eb-975a-04061a3271d6.png)
![Terraodoo4](https://user-images.githubusercontent.com/5569632/99813714-efbce480-2b3f-11eb-9768-42f5daa0cc3f.png)
![Terraodoo](https://user-images.githubusercontent.com/5569632/99813716-f0557b00-2b3f-11eb-8fab-db3d1828dc2b.png)

Few different styles...

**Comment by ska-ibees** [comment]
@JuanDCG  Please see above to compare.

**Comment by JuanDCG** [comment]
Here will be the branch with Logo PR

**Comment by JuanDCG** [comment]
We have already added the new proposal logo of @Navana

Thank you very much for your new logo proposal @ska-ibees 

I appreciate it a lot.
