### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Navana** [TerradooCloud/documentation#19]
Hello Juan,

I have been taking a look at your project and your logo idea and I would like to show you some ideas. Please, let me know what you think about it. :)

A greeting.

![LogoTerradooCloud1](https://user-images.githubusercontent.com/8069297/100151376-57a55f00-2ea1-11eb-8283-d75489eac051.png)

![LogoTerradooCloud2](https://user-images.githubusercontent.com/8069297/100151330-4c523380-2ea1-11eb-9703-6b391cd3e152.png)

![LogoTerradooCloud3](https://user-images.githubusercontent.com/8069297/100151390-5d02a980-2ea1-11eb-9c59-55eda4c08946.png)

**Comment by Navana** [comment]
And here a new logo with the official Odoo colors.

![LogoTerradooCloud4](https://user-images.githubusercontent.com/8069297/100154119-642bb680-2ea5-11eb-98b0-d71f11043e0e.png)

**Comment by JuanDCG** [comment]
Hello Navana,

Ohhh, I love it.

I've been trying to interpret your design.

The dodecahedron could mean like a cloud project with this number of sides.

Or could match with The Twelve Factor Pattern APP Design.

It's a great idea, I like it a lot.

I choose the dodecahedron, but I'm not sure about mixing colors and the circle.

Do you have a background about conceptual art ? Or art design?

What do you think about color mixing?

And about the circle ?

Thank you a lot,

Greetings

**Comment by JuanDCG** [comment]
> And here a new logo with the official Odoo colors.

Ok, thanks, the Official Odoo colors(purple) should be at `doo`.

But, what do you think about?

**Comment by JuanDCG** [comment]
> Official Odoo colors(purple)

I've searched it: #572364

**Comment by JuanDCG** [comment]
Tonight I've been thinking about your design. So, I like your design/idea

Could you please test on your drawboard the next color mixing:

Dodecahedron: `dark-red`
Terra: `dark-green`
doo: `purple`
Cloud: `dark-blue` or `white outline or fill`

I would like to erase the circle around.

Thanks

**Comment by JuanDCG** [comment]
> Do you have a background about conceptual art ? Or art design?

Ok, I check now at your profile that you have a strong background as computer engineer and as concept artist.

It is great, you have great mix of skills !

**Comment by Navana** [comment]
Yes, the idea of the dodecahedron is to represent the interconnection that exists in the Cloud, in addition to being a very harmonious geometric shape.

Here you have the design with the colors you have suggested, and others with the colors I took for the previous designs.

![LogoTerradooCloud8](https://user-images.githubusercontent.com/8069297/100217799-2b76f600-2f14-11eb-9af5-8c89150fe863.png)
![LogoTerradooCloud7](https://user-images.githubusercontent.com/8069297/100217802-2d40b980-2f14-11eb-8db9-3acf38b22737.png)
![LogoTerradooCloud6](https://user-images.githubusercontent.com/8069297/100217819-33369a80-2f14-11eb-8511-1d4268a629fd.png)
![LogoTerradooCloud5](https://user-images.githubusercontent.com/8069297/100217840-37fb4e80-2f14-11eb-91c6-aefdc84829ac.png)

**Comment by JuanDCG** [comment]
> Yes, the idea of the dodecahedron is to represent the interconnection that exists in the Cloud, in addition to being a very harmonious geometric shape.

Perfect, I like a lot your idea.

I like the fist design color mixing, but what is your opinion since is your proposal?

**Comment by JuanDCG** [comment]
@ska-ibees 

What is your opinion about this new logo proposal?

**Comment by ska-ibees** [comment]
> 
> 
> And here a new logo with the official Odoo colors.
> 
> ![LogoTerradooCloud4](https://user-images.githubusercontent.com/8069297/100154119-642bb680-2ea5-11eb-98b0-d71f11043e0e.png)

Your concept is briliant. Thanks @Navana !

What about thicker lines in dodecahedron  and "doo" in odoo's official color and rest of the text in green?

Also, having a tag line along inside of the top of the circle with a tag line like  "Multi-Cloud Native Odoo" @JuanDCG what do you think? Having a tag line will further make it esay to understand the project scope.

**Comment by JuanDCG** [comment]
> thicker lines in dodecahedron

+1

> Having a tag line will further make it esay to understand the project scope.

I don't want taint the project scope either the language itself with any tag line. The tag line are reserved for slug on url for SEO.

**Comment by JuanDCG** [comment]
> I like the fist design color mixing

To my like.

**Comment by Navana** [comment]
¿What about like this?

![LogoTerradooCloud4](https://user-images.githubusercontent.com/8069297/100279465-df08d600-2f66-11eb-9dc9-cdc32947eb07.png)

**Comment by JuanDCG** [comment]
> ![LogoTerradooCloud8](https://user-images.githubusercontent.com/8069297/100217799-2b76f600-2f14-11eb-9af5-8c89150fe863.png)

I like this design, but with thicker lines.

But only is my opinion.

**Comment by Navana** [comment]
This is the logo with thicker lines. 

In my opinion, visually, four different colors that are not even close in the light spectrum (that is, they don't belong to the same range of blues, or the same range of reds, for example) are too many, but you can decide.  :)
 
![LogoTerradooCloud8](https://user-images.githubusercontent.com/8069297/100389660-3f167f80-302e-11eb-8013-60f49dc01923.png)

**Comment by ska-ibees** [comment]
> 
> 
> ¿What about like this?
> 
> ![LogoTerradooCloud4](https://user-images.githubusercontent.com/8069297/100279465-df08d600-2f66-11eb-9dc9-cdc32947eb07.png)

This looks more professional to me.

**Comment by ska-ibees** [comment]
> 
> 
> This is the logo with thicker lines.
> 
> In my opinion, visually, four different colors that are not even close in the light spectrum (that is, they don't belong to the same range of blues, or the same range of reds, for example) are too many, but you can decide. :)
> 
> ![LogoTerradooCloud8](https://user-images.githubusercontent.com/8069297/100389660-3f167f80-302e-11eb-8013-60f49dc01923.png)

💯 Agreed.

**Comment by JuanDCG** [comment]
Ok, thank you for your feedback.

Maybe two colors: dark-red and dark-green( words )... Is it contrasted at light spectrum?

Or maybe only one color: all with dark-red ???

**Comment by Navana** [comment]
Here they are:

![LogoTerradooCloud9](https://user-images.githubusercontent.com/8069297/100622247-ed694000-3320-11eb-831d-77b6838e9a21.png)
![LogoTerradooCloud10](https://user-images.githubusercontent.com/8069297/100622255-efcb9a00-3320-11eb-9fad-720409fc1947.png)

**Comment by JuanDCG** [comment]
OK, thanks a lot.

I love the first design, but maybe with thicker lines.

I choose it.

When you have thicker lines the next steps should be:

Export it as .png and .ico.

Fork documentation and website repositories.

Overwrite the images at folders.

One Pull request per repository.

**Comment by Navana** [comment]
¿Is it ok like this?

![LogoTerradooCloud11](https://user-images.githubusercontent.com/8069297/100716135-91ea9100-33b8-11eb-8075-5e60ceddc5f4.png)

**Comment by JuanDCG** [comment]
Ok, I choose it.

I've received your logos by email.

I'm going to update with this proposal.

Thank you very much @Navana
